# Generated by Django 4.2.23 on 2026-05-15 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('current_stage', models.CharField(choices=[('intro', 'Introduction'), ('warmup', 'Warmup'), ('technical_basic', 'Technical Basic'), ('technical_intermediate', 'Technical Intermediate'), ('technical_advanced', 'Technical Advanced'), ('behavioral', 'Behavioral'), ('final', 'Final'), ('ended', 'Ended')], default='intro', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overall_score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('problem_solving_score', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('stage', models.CharField(max_length=50)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_interviewer.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('better_answer', models.TextField(blank=True)),
                ('answer_quality', models.CharField(choices=[('strong', 'Strong'), ('average', 'Average'), ('weak', 'Weak')], default='average', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai_interviewer.interviewquestion')),
            ],
        ),
    ]
