# Generated by Django 4.2.23 on 2026-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='mentioned_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='strong_topics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='weak_topics',
            field=models.TextField(blank=True),
        ),
    ]
