# Generated by Django 4.2.23 on 2026-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviewer', '0002_interviewsession_candidate_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='conversation_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='strong_answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='weak_answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
