# Generated by Django 4.2.23 on 2025-09-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
