# Generated by Django 4.2.23 on 2025-08-28 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.RemoveField(
            model_name='session',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='session',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.CharField(default='General Session', max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
