# Generated by Django 4.2.23 on 2025-08-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_session_is_online_session_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.skill'),
        ),
    ]
