# Generated by Django 4.2.23 on 2025-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_session_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_teach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wants_to_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
