# Generated by Django 4.2.23 on 2025-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_customuser_can_teach_customuser_wants_to_learn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_teach',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wants_to_learn',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
